name: Go code tests
on: [push, pull_request]
jobs:
  build_lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go compiler
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Build binary
        run: |
          go get -t ./...
          make
      - name: Go test
        run: |
          go test -v ./...
          go test -cpu=2 -race -v ./...
      - name: Check Translations
        run: |
          go build -o ci/transcheck/transcheck ci/transcheck/transcheck.go
          ./ci/transcheck/transcheck --source-dir "src" --translations-dir "examples/translations"
