name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Install Go
        uses: actions/setup-go@v2

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: "Build & test"
        run: |
          make arch

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            arch/*.tar.gz
